apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T13:27:01Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "496"
  uid: cdf34ac8-2eeb-4697-ae04-9d1ec209d9af
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.128.179
  clusterIPs:
  - 10.98.128.179
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31411
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
